### ISSUE TITLE
Foooxus no longer works with new version of Fooocus

### ISSUE THREAD

**Issue by epixia** [toutjavascript/FoooXus-Fooocus-Extender#14]
Love what you did thank your efforts. I beleie Foooxus no longer works with latest version of Fooocus

Great! FoooXus is now connected to Fooocus
pingFooocus() failed. Trying to find the right gradio API fn_index (11+0)
pingFooocus() failed. Trying to find the right gradio API fn_index (11+1)
pingFooocus() failed. Trying to find the right gradio API fn_index (11+2)
pingFooocus() failed. Trying to find the right gradio API fn_index (11+3)
pingFooocus() failed. Trying to find the right gradio API fn_index (11+4)
pingFooocus() failed. Trying to find the right gradio API fn_index (11+5)
pingFooocus() failed. Trying to find the right gradio API fn_index (11+6)
pingFooocus() failed. Trying to find the right gradio API fn_index (11+7)
pingFooocus() failed. Trying to find the right gradio API fn_index (11+8)
pingFooocus() failed. Trying to find the right gradio API fn_index (11+9)
pingFooocus() failed. Trying to find the right gradio API fn_index (11+10)
Exception Error on api.py/pingFooocus():
  TypeError("argument of type 'NoneType' is not iterable")
FoooXus is not connected to Fooocus gradio API :(
 - Fooocus must be running, on the same device
 - Fooocus must be at least 2.4.1
 - If FoooXus app has already worked, Fooocus may have changed version.
   it may break API calls

**Comment by toutjavascript** [comment]
New release is live and works with last Fooocus version
