### ISSUE TITLE
FoooXus not finding anny LoRAs

### ISSUE THREAD

**Issue by Ok2dot0** [toutjavascript/FoooXus-Fooocus-Extender#7]
FoooXus can't find any LoRAs, even if there are obvious ones, even in the directory where it says there's nothing in it.
![grafik](https://github.com/toutjavascript/FoooXus-Fooocus-Extender/assets/93327029/be9eec95-1e9b-4588-8dfe-f4e3fda43a36)

**Comment by toutjavascript** [comment]
Is it the right folder ?
Can it find the models ?

**Comment by Ok2dot0** [comment]
Yeah, even if I take the path from the error message and paste it into the explorer, the folder is filled with .safetensors LoRA files. And Focus on its own recognizes them.

**Comment by toutjavascript** [comment]
Strange issue
I will try to reproduce that

Do you confirm that models are identified ?

**Comment by Ok2dot0** [comment]
Do you mean like in the Fooocus web-ui?
![grafik](https://github.com/toutjavascript/FoooXus-Fooocus-Extender/assets/93327029/caddc27f-71dd-4521-8af9-7cd748113c56)

And something that maybe could help; in the Stable-Diffusion web-ui, you need to tick an option called: “Always show all networks on the Lora page”. Perhaps FoooXus tries to identify the kind of the .safetensor files, but is unable to do so. This could be the issue. But IDK.

And also a short question. Is the API feature in FoooXus work? It would be super useful for me. And thank you for such an incredible piece of software.

**Comment by toutjavascript** [comment]
Hello
I published a new release.
You can now add a new line with the real folder (not symbolic link) in config.json
   "loras-directory": "D:\\datas\\StabilityMatrix\\Data\\Models\\Lora",

Can you test it please ?

Thanks for your messages and help
API are not available. This is my very first python project.
I must work on it.

**Comment by Ok2dot0** [comment]
Huge! Thank you. Everything is now working fine:
![grafik](https://github.com/toutjavascript/FoooXus-Fooocus-Extender/assets/93327029/b91a9edd-b59d-459b-b472-0babf363f54a)
